08-23 15:22:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.e.M(mef:39)
	at com.thebrain.common.b.e.M(mef:231)
	at com.thebrain.common.b.e.M(mef:128)
	at com.thebrain.personal.a.a.l.i(zhd:729)
	at com.thebrain.c.e.v.L(cdg:406)
	at com.thebrain.personal.a.a.t.f(kid:307)
	at com.thebrain.personal.view.bi.M(bcd:4043)
	at com.thebrain.personal.view.bi.n(bcd:5420)
	at com.thebrain.personal.view.bi.t(bcd:4142)
	at com.thebrain.personal.view.kc.run(bcd:3823)
	at java.lang.Thread.run(Unknown Source)
08-23 18:04:52 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.e.M(mef:39)
	at com.thebrain.common.b.e.M(mef:231)
	at com.thebrain.common.b.e.M(mef:128)
	at com.thebrain.personal.a.a.l.i(zhd:729)
	at com.thebrain.c.e.v.L(cdg:406)
	at com.thebrain.personal.a.a.t.f(kid:307)
	at com.thebrain.personal.view.bi.M(bcd:4043)
	at com.thebrain.personal.controller.App.f(oqd:1143)
	at com.thebrain.personal.view.rd.run(bcd:1938)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.thebrain.personal.c.d.d.dispatchEvent(tdd:239)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
08-26 09:40:17 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.e.M(mef:39)
	at com.thebrain.common.b.e.M(mef:231)
	at com.thebrain.common.b.e.M(mef:128)
	at com.thebrain.personal.a.a.l.i(zhd:729)
	at com.thebrain.c.e.v.L(cdg:406)
	at com.thebrain.personal.a.a.t.f(kid:307)
	at com.thebrain.personal.view.bi.M(bcd:4043)
	at com.thebrain.personal.view.bi.n(bcd:5420)
	at com.thebrain.personal.view.bi.t(bcd:4142)
	at com.thebrain.personal.view.kc.run(bcd:3823)
	at java.lang.Thread.run(Unknown Source)
09-26 15:29:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.e.M(mef:39)
	at com.thebrain.common.b.e.M(mef:231)
	at com.thebrain.common.b.e.M(mef:128)
	at com.thebrain.personal.a.a.l.i(zhd:729)
	at com.thebrain.c.e.v.L(cdg:406)
	at com.thebrain.personal.a.a.t.f(kid:307)
	at com.thebrain.personal.view.bi.M(bcd:4043)
	at com.thebrain.personal.view.bi.n(bcd:5420)
	at com.thebrain.personal.view.bi.t(bcd:4142)
	at com.thebrain.personal.view.kc.run(bcd:3823)
	at java.lang.Thread.run(Unknown Source)
09-26 15:32:40 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-164]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1393)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1371)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:191)
	at com.thebrain.common.b.e.M(mef:39)
	at com.thebrain.common.b.e.M(mef:231)
	at com.thebrain.common.b.e.M(mef:128)
	at com.thebrain.personal.a.a.l.i(zhd:729)
	at com.thebrain.c.e.v.L(cdg:406)
	at com.thebrain.personal.a.a.t.f(kid:307)
	at com.thebrain.personal.view.bi.M(bcd:4043)
	at com.thebrain.personal.view.bi.n(bcd:5420)
	at com.thebrain.personal.view.bi.t(bcd:4142)
	at com.thebrain.personal.view.kc.run(bcd:3823)
	at java.lang.Thread.run(Unknown Source)
